# Generated by Django 4.2 on 2025-12-03

from django.db import migrations
import os


def force_reset_superuser_password(apps, schema_editor):
    """
    Force reset do password do superusuário usando variáveis de ambiente
    """
    User = apps.get_model('auth', 'User')
    username = os.environ.get('DJANGO_SUPERUSER_USERNAME', 'admin')
    email = os.environ.get('DJANGO_SUPERUSER_EMAIL', 'admin@regionalveiculos.com')
    password = os.environ.get('DJANGO_SUPERUSER_PASSWORD', 'RegionalVeiculos2024!')
    
    try:
        # Procurar o usuário admin
        user = User.objects.filter(username=username).first()
        
        if user:
            print(f'🔄 Forçando reset da senha do usuário "{username}"...')
            user.set_password(password)
            user.email = email
            user.is_staff = True
            user.is_superuser = True
            user.is_active = True
            user.save()
            print(f'✅ Senha do usuário "{username}" foi resetada com sucesso!')
        else:
            print(f'🆕 Criando novo superusuário "{username}"...')
            User.objects.create_superuser(
                username=username,
                email=email,
                password=password
            )
            print(f'✅ Superusuário "{username}" criado com sucesso!')
            
    except Exception as e:
        print(f'❌ Erro ao resetar senha do superusuário: {e}')
        import traceback
        traceback.print_exc()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_create_superuser'),
    ]

    operations = [
        migrations.RunPython(force_reset_superuser_password, reverse_code=migrations.RunPython.noop),
    ]
