# Generated by Django 4.2 on 2025-12-03

from django.db import migrations


def clean_problematic_images(apps, schema_editor):
    """
    Remove imagens problemáticas do tipo carro_flutuante que podem estar
    causando conflitos com o Cloudinary
    """
    ImagemSite = apps.get_model('core', 'ImagemSite')
    
    # Remover todas as imagens carro_flutuante existentes
    deleted_count, _ = ImagemSite.objects.filter(tipo='carro_flutuante').delete()
    
    if deleted_count > 0:
        print(f'✅ Removidas {deleted_count} imagens problemáticas do tipo carro_flutuante')
    else:
        print('ℹ️ Nenhuma imagem problemática encontrada')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_force_superuser_password_reset'),
    ]

    operations = [
        migrations.RunPython(clean_problematic_images, reverse_code=migrations.RunPython.noop),
    ]