# Generated by Django 4.2 on 2025-12-03

from django.db import migrations


def clean_all_site_images(apps, schema_editor):
    """
    Remove todas as imagens do modelo ImagemSite que podem estar causando
    problemas de auto-save e thumbnails no Cloudinary
    """
    ImagemSite = apps.get_model('core', 'ImagemSite')
    
    # Remover todas as imagens problemáticas
    deleted_count, details = ImagemSite.objects.all().delete()
    
    if deleted_count > 0:
        print(f'✅ Removidas {deleted_count} imagens do modelo ImagemSite')
        print('ℹ️ Sistema agora usa apenas imagens estáticas')
    else:
        print('ℹ️ Nenhuma imagem encontrada para remoção')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_clean_problematic_images'),
    ]

    operations = [
        migrations.RunPython(clean_all_site_images, reverse_code=migrations.RunPython.noop),
    ]