# Generated by Django 4.2 on 2025-12-03

from django.db import migrations


def setup_site_images_correctly(apps, schema_editor):
    """
    Configura corretamente as imagens do site para uso dinâmico
    sem problemas de auto-save
    """
    ImagemSite = apps.get_model('core', 'ImagemSite')
    
    # Não cria nenhuma imagem automaticamente
    # As imagens devem ser adicionadas manualmente pelo admin
    # quando necessário
    
    print('ℹ️ Sistema configurado para aceitar imagens dinâmicas')
    print('📝 Adicione imagens pelo admin em: /admin/core/imagemsite/')
    print('🎯 Tipos disponíveis: carro_flutuante, sobre_loja, banner_home')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_clean_all_site_images'),
    ]

    operations = [
        migrations.RunPython(setup_site_images_correctly, reverse_code=migrations.RunPython.noop),
    ]